#define BUTTONBOARD_PANIC                 8
#define BUTTONBOARD_DROP_INTAKE           3
#define BUTTONBOARD_RAISE_INTAKE          4
#define BUTTONBOARD_MACRO_INTAKE          5
#define BUTTONBOARD_INDEXER_UP            11
#define BUTTONBOARD_INDEXER_DOWN          13
#define BUTTONBOARD_SHOOTERSPEED_LOW      6
#define BUTTONBOARD_SHOOTERSPEED_VARIABLE 10
#define BUTTONBOARD_SHOOTER_AXIS          2
#define BUTTONBOARD_AXIS_SPEEDLIMIT       0
#define BUTTONBOARD_SHOOTER               12
#define BUTTONBOARD_SHOOTER_MACRO         9
#define BUTTONBOARD_MACRO_SHOOT           BUTTONBOARD_SHOOTER_MACRO

#define XBOX_JOYSTICK_INDEXER_UP   6
#define XBOX_JOYSTICK_INDEXER_DOWN 4
#define XBOX_JOYSTICK_LEFT_Y       1
#define XBOX_JOYSTICK_RIGHT_Y      5
#define XBOX_JOYSTICK_LEFT_X       -1
#define XBOX_JOYSTICK_RIGHT_X      -1

#define BUTTONBOARD_CONTROLLER_SLOT 3
#define XBOX_CONTROLLER_SLOT        4
